[package]
name = "qobuz-player-controls"

version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
qobuz-api = { version = "*", path = "../qobuz-api" }

gstreamer = { workspace = true, features = ["serde", "v1_16"] }
cached = { workspace = true, features = ["async", "serde", "serde_json"] } 
once_cell = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["full"] }
rand = { workspace = true }
tracing = { workspace = true }
async-broadcast = { workspace = true }
serde = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
snafu = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "sqlite", "migrate", "macros"] }
dirs = { workspace = true }
chrono = { workspace = true }
zbus = { workspace = true, features = ["tokio"] }
